package progettofinale.sailingclub.communication;

public enum ResponseType {

    OK,
    NOT_BOAT,
    RMV_BOAT_SUCCESS,
    ERROR_RMV_BOAT,
    ADD_BOAT_SUCCESS,
    ADD_MEMBER_SUCCESS,
    RMV_MEMBER_SUCCESS,
    ERROR_ADD_MEMBER,
    ERROR_ADD_BOAT,
    NOT_AUTHORIZED,
    NOT_FOUND,
    CONNECTION_ERROR,
    ERROR,
    INVALID_VAT,
    ALREADY_EXISTING,
    NOT_RACE,
    NOT_INSCRIPTION,
    ADD_RACE_SUCCESS,
    ERROR_ADD_RACE,
    RMV_RACE_SUCCESS,
    ADD_PARTICIPATION_SUCCESS,
    ERROR_ADD_PARTICIPATION,
    PAY_STORAGE_SUCCESS,
    PAY_MEMBERSHIP_SUCCESS,
    EXPIRED,
    NOT_EXPIRED,
    N_STORAGE,
    N_MEMBERSHIP,
    NOTICE_ALL

}
